version: "3.1"

services:
  vstore-api:
    container_name: vstore-api
    image: vstore-api
    environment:
      - PORT=5000
    ports:
      - 5000:5000
    build:
      context: .
      dockerfile: Dockerfile
